
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

# Do not prefer various `%` ways of specifying things in Ruby - I
# think these are less clear and unnecessary
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false

# Do not preder trailing commas in multi-line hash/array literals - better as
# when something is added to a literal the previous last line does not also
# need to be changed, which also makes diffs smaller
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# Do not require documentation for top-level classes or modules - seems
# unnecessary for the project at the moment.
Style/Documentation:
  Enabled: false

# Do not limit block length - fails for any significant RSpec test file.
Metrics/BlockLength:
  Enabled: false

# We trust the YAML we're loading, so don't warn if we don't use
# `YAML.safe_load` instead of `YAML.load`.
Security/YAMLLoad:
  Enabled: false

# I don't care if we use the compact way of declaring classes and modules.
Style/ClassAndModuleChildren:
  Enabled: false

# If we need a boolean value, having it actually be a boolean rather than
# checking if it is nil or not is clearer IMO, and `!!value` is a standard way
# to get this.
Style/DoubleNegation:
  Enabled: false
