
# Config file for false positives to ignore (or other things don't care about)
# when running https://github.com/joshuaclayton/unused.

- name: Ruby
  autoLowLikelihood:

    # Ignore all dependency functions.
    - name: dependency functions
      pathStartsWith: scripts/dependencies

    # Ignore everything in prototype GUI.
    - name: GUI
      pathStartsWith: src/gui

    # Ignore patches for Gems; will often monkey-patch methods to be called by
    # Gem code which would otherwise be flagged up.
    - name: Gem patch methods
      pathStartsWith: src/patches

    - name: Configurator::Question asker methods
      pathStartsWith: src/configurator
      termStartsWith: ask_

    - name: Miscellaneous other terms
      allowedTerms:
      - MetalBench
      - debug!
