
ruby '2.4.1'
source 'https://rubygems.org'

gem 'commander'
gem 'rugged'
gem 'activesupport'
gem 'recursive-open-struct'
gem 'pcap', git: 'https://github.com/alces-software/ruby-pcap.git'
gem 'net-dhcp'
gem 'hashie'

group :test do
  gem 'rspec'
  gem 'simplecov'
end
